#!/bin/sh
set -e

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║            CMMC Tracker - Docker Startup                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if SSL certificates exist (generated by docker-start.sh or mounted)
if [ ! -f "./certs/cert.pem" ] || [ ! -f "./certs/key.pem" ]; then
    echo "[WARN] SSL certificates not found in ./certs/"
    echo "[WARN] Generate them first with: ./docker-start.sh"
    echo "[WARN] Or mount certs directory in docker-compose.yml"
    echo "[INFO] Attempting to generate certificates..."
    
    mkdir -p ./certs
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout ./certs/key.pem \
        -out ./certs/cert.pem \
        -subj "/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null || {
        echo "[ERROR] Could not generate certificates. Exiting."
        exit 1
    }
fi

echo "[OK] SSL certificates ready"

# Wait for database to be ready
echo "[INFO] Waiting for database..."
RETRIES=30
while [ $RETRIES -gt 0 ]; do
    if npx prisma db execute --stdin <<< "SELECT 1;" > /dev/null 2>&1; then
        echo "[OK] Database is ready"
        break
    fi
    echo "[INFO] Database not ready yet, retrying in 2s... ($RETRIES attempts left)"
    sleep 2
    RETRIES=$((RETRIES - 1))
done

if [ $RETRIES -eq 0 ]; then
    echo "[ERROR] Database connection failed after 30 attempts"
    exit 1
fi

# Run migrations
echo "[INFO] Running database migrations..."
npx prisma migrate deploy
echo "[OK] Migrations applied"

# Seed database if empty
USER_COUNT=$(npx prisma db execute --stdin <<< "SELECT COUNT(*) FROM users;" 2>/dev/null | tr -d ' \n' || echo "0")
if [ "$USER_COUNT" = "0" ]; then
    echo "[INFO] Database is empty. Seeding..."
    if [ -f "./prisma/seed.ts" ]; then
        npx tsx ./prisma/seed.ts || true
    fi
    if [ -f "./seed-data.sql" ]; then
        npx prisma db execute --file ./seed-data.sql || true
    fi
    echo "[OK] Database seeded"
else
    echo "[OK] Database already has $USER_COUNT users"
fi

# Start the HTTPS server
echo ""
echo "[OK] Starting CMMC Tracker HTTPS Server..."
echo ""

exec node server.js
