-- Full seed script for CMMC Tracker v2.1
-- Run this in the database container after deployment

-- Admin user (password: admin123)
INSERT INTO users (id, name, email, password_hash, role, created_at)
VALUES (
  gen_random_uuid(),
  'Admin User',
  'admin@local',
  '$2b$10$EF2DJNSnZvgHGCb78pDtG.Cg/5rW3nGp9Wd9dStyVCXMKPrwwGD1u',
  'Admin',
  NOW()
)
ON CONFLICT (email) DO UPDATE SET
  password_hash = EXCLUDED.password_hash,
  name = EXCLUDED.name,
  role = EXCLUDED.role;

-- Chat rooms
INSERT INTO chat_rooms (id, name, type, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'global', 'Global', NOW(), NOW()),
  (gen_random_uuid(), 'private', 'Private', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- 108 CMMC Controls
INSERT INTO controls (id, control_id, domain, title, description, status, updated_at) VALUES
(gen_random_uuid(), '3.1.1', 'Access Control (AC)', 'Limit system access to authorized users', 'Limit information system access to authorized users.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.2', 'Access Control (AC)', 'Limit system access to types of transactions', 'Limit information system access to the types of transactions that authorized users are permitted to execute.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.3', 'Access Control (AC)', 'Control flow of CUI', 'Control the flow of CUI in accordance with approved authorizations.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.4', 'Access Control (AC)', 'Separation of duties', 'Separate the duties of individuals to reduce the risk of malevolent activity without collusion.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.5', 'Access Control (AC)', 'Least privilege', 'Employ the principle of least privilege, allowing only authorized accesses necessary to accomplish assigned tasks.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.6', 'Access Control (AC)', 'Non-privileged access for nonsecurity functions', 'Use non-privileged accounts when performing nonsecurity functions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.7', 'Access Control (AC)', 'Prevent non-privileged users from executing privileged functions', 'Prevent non-privileged users from executing privileged functions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.8', 'Access Control (AC)', 'Limit unsuccessful logon attempts', 'Limit the number of unsuccessful logon attempts.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.9', 'Access Control (AC)', 'Privacy and security notices', 'Provide privacy and security notices consistent with applicable CUI rules.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.10', 'Access Control (AC)', 'Use session lock', 'Use session lock with pattern-hiding display to prevent access/viewing.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.11', 'Access Control (AC)', 'Terminate sessions after inactivity', 'Terminate sessions after a defined period of inactivity.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.12', 'Access Control (AC)', 'Monitor and control remote access', 'Monitor and control remote access sessions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.13', 'Access Control (AC)', 'Employ cryptographic mechanisms', 'Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.14', 'Access Control (AC)', 'Route remote access through managed points', 'Route remote access via managed access control points.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.15', 'Access Control (AC)', 'Authorize wireless access', 'Authorize wireless access prior to allowing such connections.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.16', 'Access Control (AC)', 'Protect wireless access', 'Protect wireless access using authentication and encryption.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.17', 'Access Control (AC)', 'Control mobile device access', 'Control connection of mobile devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.18', 'Access Control (AC)', 'Encrypt mobile device data', 'Encrypt CUI on mobile devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.19', 'Access Control (AC)', 'Restrict USB devices', 'Restrict use of organization-defined portable storage devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.20', 'Access Control (AC)', 'Limit external connections', 'Limit external system connections.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.21', 'Access Control (AC)', 'Control public information', 'Control CUI posted on publicly accessible systems.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.1.22', 'Access Control (AC)', 'Control CUI in shared resources', 'Control CUI in shared system resources.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.2.1', 'Awareness & Training (AT)', 'Security awareness training', 'Ensure that managers, system administrators, and users are aware of security risks.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.2.2', 'Awareness & Training (AT)', 'Insider threat training', 'Provide insider threat awareness training.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.2.3', 'Awareness & Training (AT)', 'Role-based training', 'Provide role-based security training.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.1', 'Audit & Accountability (AU)', 'Create and retain audit logs', 'Create and retain system audit logs.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.2', 'Audit & Accountability (AU)', 'Ensure audit events are reviewed', 'Ensure that the auditing system is reviewed.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.3', 'Audit & Accountability (AU)', 'Protect audit information', 'Protect audit information.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.4', 'Audit & Accountability (AU)', 'Audit failure alerts', 'Alert on audit processing failures.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.5', 'Audit & Accountability (AU)', 'Correlate audit records', 'Correlate audit record review, analysis, and reporting.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.6', 'Audit & Accountability (AU)', 'Provide audit reduction', 'Provide audit reduction and report generation.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.7', 'Audit & Accountability (AU)', 'Time stamps', 'Provide time stamps for audit records.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.8', 'Audit & Accountability (AU)', 'Protection of audit info', 'Protect audit information and tools.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.3.9', 'Audit & Accountability (AU)', 'Manage audit storage capacity', 'Manage audit storage capacity.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.1', 'Configuration Management (CM)', 'Establish baseline configurations', 'Establish baseline configurations.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.2', 'Configuration Management (CM)', 'Enforce security config', 'Establish and enforce security configuration settings.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.3', 'Configuration Management (CM)', 'Track and review changes', 'Track, review, and approve changes.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.4', 'Configuration Management (CM)', 'Security impact analysis', 'Analyze security impact of changes.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.5', 'Configuration Management (CM)', 'Access restrictions for changes', 'Define, document, and enforce access restrictions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.6', 'Configuration Management (CM)', 'Least functionality', 'Employ least functionality by configuring systems to provide only essential capabilities.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.7', 'Configuration Management (CM)', 'Nonessential functions', 'Restrict nonessential programs, functions, ports, protocols, and services.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.8', 'Configuration Management (CM)', 'Software usage restrictions', 'Apply software usage restrictions for nonessential software.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.9', 'Configuration Management (CM)', 'User-installed software', 'Control user installation of software.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.10', 'Configuration Management (CM)', 'Component inventory', 'Create and maintain an inventory of system components.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.4.11', 'Configuration Management (CM)', 'Memory protection', 'Employ mechanisms to protect memory.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.1', 'Identification & Authentication (IA)', 'Identify system users', 'Identify system users, processes, and devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.2', 'Identification & Authentication (IA)', 'Authenticate identities', 'Authenticate identities of users, processes, and devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.3', 'Identification & Authentication (IA)', 'Multi-factor authentication', 'Use multi-factor authentication for local and network access.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.4', 'Identification & Authentication (IA)', 'Replay-resistant auth', 'Employ replay-resistant authentication mechanisms.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.5', 'Identification & Authentication (IA)', 'Prevent identifier reuse', 'Prevent reuse of identifiers for a defined period.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.6', 'Identification & Authentication (IA)', 'Disable identifiers after inactivity', 'Disable inactive identifiers after defined period.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.7', 'Identification & Authentication (IA)', 'Password complexity', 'Enforce minimum password complexity requirements.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.8', 'Identification & Authentication (IA)', 'Password lifetime restrictions', 'Prohibit password reuse for specified generations.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.9', 'Identification & Authentication (IA)', 'Temporary passwords', 'Allow temporary passwords with immediate change upon first login.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.10', 'Identification & Authentication (IA)', 'Store passwords with encryption', 'Store and transmit passwords with encryption.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.5.11', 'Identification & Authentication (IA)', 'Obscure feedback of authentication', 'Obscure feedback of authentication information.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.6.1', 'Incident Response (IR)', 'Incident response policy', 'Establish an operational incident-handling capability.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.6.2', 'Incident Response (IR)', 'Track and document incidents', 'Track, document, and report incidents.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.6.3', 'Incident Response (IR)', 'Test incident response', 'Test the incident response capability.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.7.1', 'Maintenance (MA)', 'Perform maintenance', 'Perform maintenance on organizational systems.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.7.2', 'Maintenance (MA)', 'Controlled maintenance', 'Provide controls on the tools used for maintenance.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.7.3', 'Maintenance (MA)', 'Sanitize equipment', 'Ensure equipment removed for off-site maintenance is sanitized.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.7.4', 'Maintenance (MA)', 'Maintenance personnel', 'Supervise maintenance personnel.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.7.5', 'Maintenance (MA)', 'Nonlocal maintenance', 'Restrict nonlocal maintenance sessions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.7.6', 'Maintenance (MA)', 'Cryptographic protection for nonlocal maintenance', 'Protect nonlocal maintenance via cryptographic mechanisms.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.1', 'Media Protection (MP)', 'Protect system media', 'Protect system media containing CUI.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.2', 'Media Protection (MP)', 'Limit access to media', 'Limit access to CUI on media to authorized users.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.3', 'Media Protection (MP)', 'Sanitize media', 'Sanitize media prior to disposal or release.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.4', 'Media Protection (MP)', 'Mark media', 'Mark media with necessary CUI markings and distribution limitations.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.5', 'Media Protection (MP)', 'Control media transport', 'Control media transport in approved areas.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.6', 'Media Protection (MP)', 'Protect backups', 'Protect system backups containing CUI.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.7', 'Media Protection (MP)', 'Restrict USB device usage', 'Restrict USB device usage.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.8', 'Media Protection (MP)', 'Prohibit use of portable storage without approval', 'Prohibit use of portable storage devices without explicit approval.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.8.9', 'Media Protection (MP)', 'Encrypt backups', 'Encrypt system backup media containing CUI.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.9.1', 'Personnel Security (PS)', 'Screen personnel', 'Screen personnel prior to authorizing access.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.9.2', 'Personnel Security (PS)', 'Ensure CUI protection during personnel actions', 'Ensure CUI protections during personnel actions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.10.1', 'Physical Protection (PE)', 'Limit physical access', 'Limit physical access to systems.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.10.2', 'Physical Protection (PE)', 'Escort visitors', 'Escort visitors and monitor visitor activity.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.10.3', 'Physical Protection (PE)', 'Control access to physical devices', 'Control physical access to devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.10.4', 'Physical Protection (PE)', 'Monitor physical access', 'Monitor physical access to facilities.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.10.5', 'Physical Protection (PE)', 'Protect devices from tampering', 'Protect devices from physical tampering.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.10.6', 'Physical Protection (PE)', 'Secure work areas', 'Secure work areas to protect CUI.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.11.1', 'Risk Assessment (RA)', 'Risk assessment policy', 'Periodically assess the risk to organizational operations.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.11.2', 'Risk Assessment (RA)', 'Scan for vulnerabilities', 'Scan for vulnerabilities in organizational systems and applications.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.11.3', 'Risk Assessment (RA)', 'Remediate vulnerabilities', 'Remediate vulnerabilities in accordance with assessments.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.11.4', 'Risk Assessment (RA)', 'Threat intelligence', 'Identify cyber supply chain risks.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.12.1', 'Security Assessment (CA)', 'Security assessments', 'Periodically assess the security controls.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.12.2', 'Security Assessment (CA)', 'Develop plans', 'Develop and implement plans for assessment.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.12.3', 'Security Assessment (CA)', 'Monitor security controls', 'Monitor security controls on an ongoing basis.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.12.4', 'Security Assessment (CA)', 'Review and update plans', 'Review and update assessment plans.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.1', 'System & Communications Protection (SC)', 'Boundary protection', 'Monitor and control communications at external boundaries.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.2', 'System & Communications Protection (SC)', 'Deny network traffic by default', 'Deny network traffic by default and allow by exception.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.3', 'System & Communications Protection (SC)', 'Separate CUI from other data', 'Separate CUI from other information.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.4', 'System & Communications Protection (SC)', 'Prevent CUI from unauthorized release', 'Prevent CUI from unauthorized release.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.5', 'System & Communications Protection (SC)', 'Implement subnetworks', 'Implement subnetworks for publicly accessible components.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.6', 'System & Communications Protection (SC)', 'Deny direct public access', 'Deny direct public access between internal and external networks.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.7', 'System & Communications Protection (SC)', 'Prevent split tunneling', 'Prevent split tunneling for remote devices.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.8', 'System & Communications Protection (SC)', 'Encrypt CUI on public networks', 'Encrypt CUI on public networks.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.9', 'System & Communications Protection (SC)', 'Encrypt CUI at rest', 'Encrypt CUI at rest on mobile devices and media.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.10', 'System & Communications Protection (SC)', 'Encrypt remote access', 'Encrypt remote access sessions.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.13.11', 'System & Communications Protection (SC)', 'FIPS-validated cryptography', 'Use FIPS-validated cryptography for CUI protection.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.1', 'System & Information Integrity (SI)', 'Flaw remediation', 'Identify, report, and correct system flaws.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.2', 'System & Information Integrity (SI)', 'Malicious code protection', 'Provide protection from malicious code.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.3', 'System & Information Integrity (SI)', 'Monitor system alerts', 'Monitor system alerts and advisories.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.4', 'System & Information Integrity (SI)', 'Update malicious code protection', 'Update malicious code protection mechanisms.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.5', 'System & Information Integrity (SI)', 'System integrity verification', 'Perform periodic scans of organizational systems.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.6', 'System & Information Integrity (SI)', 'Monitor communications', 'Monitor communications for unauthorized exfiltration.', 'Not_Started', NOW()),
(gen_random_uuid(), '3.14.7', 'System & Information Integrity (SI)', 'Identify unauthorized use', 'Identify unauthorized use of systems.', 'Not_Started', NOW());
